### ISSUE TITLE
Add a search bar

### ISSUE THREAD

**Issue by BjoernPetersen** [hawkins/always-sunny#3]
I would love to be able to search for a specific episode title. You could also search the description for the keywords...

**Comment by hawkins** [comment]
Great idea! Thanks a bunch for the suggestion.

I bet [Angular Material's Autocomplete](https://material.angularjs.org/latest/demo/autocomplete) directive would be an easy directive to use here. The custom template example looks perfect for what we need.

Any interest in giving this a shot yourself?

**Comment by BjoernPetersen** [comment]
That does look like an easy way to do this. I am, however, not interested in screwing up your project with my very poor JavaScript skills.

**Comment by hawkins** [comment]
Haha, totally understand. I'll try to knock this out once I get a chance in a week or so.

**Comment by hawkins** [comment]
Just a small update - I've wanted to port this project to React for some time, and have finally done so. I've nearly completed this feature in the React edition, all that remains is styling and a few quality of life fixes. Unfortunately I'm still a student and finals week has arrived, but hopefully I'll be able to finish this task early next week.
